/* native_backend.c — Native executable compiler backend for Snovalang. */
#ifndef _POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
#endif
#ifndef _DEFAULT_SOURCE
#define _DEFAULT_SOURCE
#endif

#include "native_backend.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

int sn_native_compile(const SnBCUnit *bc, const SnTargetInfo *target, const char *output_path) {
    if (!bc || !target || !output_path) {
        return 0;
    }

    char c_source_path[1024];
    snprintf(c_source_path, sizeof(c_source_path), "%s.runner.c", output_path);

    FILE *f = fopen(c_source_path, "w");
    if (!f) {
        fprintf(stderr, "error: cannot create temporary build source %s\n", c_source_path);
        return 0;
    }

    /* Emit self-contained C runtime with embedded bytecode, pulsar threading, and async loop */
    fprintf(f, "/* Auto-generated by snovac native backend */\n");
    fprintf(f, "#define _POSIX_C_SOURCE 200809L\n");
    fprintf(f, "#define _DEFAULT_SOURCE\n");
    fprintf(f, "#include <stdio.h>\n");
    fprintf(f, "#include <stdlib.h>\n");
    fprintf(f, "#include <string.h>\n");
    fprintf(f, "#include <stdint.h>\n");
    fprintf(f, "#include <stdbool.h>\n");

    if (target->os == SN_OS_WINDOWS) {
        fprintf(f, "#include <windows.h>\n");
        fprintf(f, "#include <process.h>\n");
    } else {
        fprintf(f, "#include <pthread.h>\n");
        fprintf(f, "#include <unistd.h>\n");
    }
    fprintf(f, "\n");

    /* Emit Bytecode strings */
    fprintf(f, "static const char *g_strings[%zu] = {\n", bc->string_pool.count ? bc->string_pool.count : 1);
    for (size_t i = 0; i < bc->string_pool.count; i++) {
        fprintf(f, "  \"");
        for (const char *p = bc->string_pool.strings[i]; *p; p++) {
            if (*p == '"') fprintf(f, "\\\"");
            else if (*p == '\\') fprintf(f, "\\\\");
            else if (*p == '\n') fprintf(f, "\\n");
            else if (*p == '\t') fprintf(f, "\\t");
            else fputc(*p, f);
        }
        fprintf(f, "\",\n");
    }
    if (bc->string_pool.count == 0) {
        fprintf(f, "  \"\"\n");
    }
    fprintf(f, "};\n\n");

    /* Emit Bytecode functions */
    for (size_t i = 0; i < bc->function_count; i++) {
        SnFunctionChunk *fn = bc->functions[i];
        fprintf(f, "static const uint8_t g_fn_code_%zu[%zu] = {", i, fn->chunk.count ? fn->chunk.count : 1);
        for (size_t ci = 0; ci < fn->chunk.count; ci++) {
            if (ci % 16 == 0) fprintf(f, "\n  ");
            fprintf(f, "0x%02x, ", fn->chunk.code[ci]);
        }
        fprintf(f, "\n};\n");
    }

    /* Emit Value types and Stack */
    fprintf(f, "\n");
    fprintf(f, "typedef enum { VAL_UNIT, VAL_BOOL, VAL_INT, VAL_DOUBLE, VAL_STRING, VAL_ARRAY, VAL_FUTURE } ValTag;\n");
    fprintf(f, "typedef struct Val Val;\n");
    fprintf(f, "struct Val { ValTag tag; union { bool b; int64_t i; double d; char *str; void *ptr; } as; };\n\n");
    fprintf(f, "static Val g_stack[4096];\nstatic Val *g_sp = g_stack;\n");
    fprintf(f, "static inline void push(Val v) { *g_sp++ = v; }\n");
    fprintf(f, "static inline Val pop(void) { return *(--g_sp); }\n");
    fprintf(f, "static inline Val peek(int d) { return g_sp[-1 - d]; }\n\n");

    fprintf(f, "static uint32_t read_u32(const uint8_t **ip) {\n");
    fprintf(f, "  uint32_t v = (uint32_t)((*ip)[0]) | ((uint32_t)((*ip)[1]) << 8) | ((uint32_t)((*ip)[2]) << 16) | ((uint32_t)((*ip)[3]) << 24);\n");
    fprintf(f, "  *ip += 4;\n  return v;\n}\n");

    fprintf(f, "static int64_t read_i64(const uint8_t **ip) {\n");
    fprintf(f, "  uint64_t v = 0;\n  for (int i = 0; i < 8; i++) v |= ((uint64_t)((*ip)[i]) << (i * 8));\n");
    fprintf(f, "  *ip += 8;\n  return (int64_t)v;\n}\n");

    fprintf(f, "static double read_double(const uint8_t **ip) {\n");
    fprintf(f, "  union { double d; uint64_t u; } cvt; cvt.u = 0;\n");
    fprintf(f, "  for (int i = 0; i < 8; i++) cvt.u |= ((uint64_t)((*ip)[i]) << (i * 8));\n");
    fprintf(f, "  *ip += 8;\n  return cvt.d;\n}\n\n");

    /* Emit Pulsar Multi-parallelism Runtime */
    fprintf(f, "/* Pulsar platform thread multi-parallelism */\n");
    fprintf(f, "typedef struct PulsarWork {\n");
    fprintf(f, "  size_t fn_idx;\n");
    fprintf(f, "  Val arg;\n");
    fprintf(f, "  struct PulsarWork *next;\n");
    fprintf(f, "} PulsarWork;\n\n");

    if (target->os == SN_OS_WINDOWS) {
        fprintf(f, "static CRITICAL_SECTION g_pulsar_mutex;\n");
        fprintf(f, "static CONDITION_VARIABLE g_pulsar_cond;\n");
    } else {
        fprintf(f, "static pthread_mutex_t g_pulsar_mutex = PTHREAD_MUTEX_INITIALIZER;\n");
        fprintf(f, "static pthread_cond_t g_pulsar_cond = PTHREAD_COND_INITIALIZER;\n");
    }
    fprintf(f, "static PulsarWork *g_pulsar_queue = NULL;\n");
    fprintf(f, "static bool g_pulsar_stop = false;\n\n");

    fprintf(f, "static int run_function(size_t fn_idx);\n\n");

    if (target->os == SN_OS_WINDOWS) {
        fprintf(f, "static unsigned __stdcall pulsar_thread_proc(void *arg) {\n");
        fprintf(f, "  (void)arg;\n");
        fprintf(f, "  for (;;) {\n");
        fprintf(f, "    EnterCriticalSection(&g_pulsar_mutex);\n");
        fprintf(f, "    while (!g_pulsar_queue && !g_pulsar_stop) {\n");
        fprintf(f, "      SleepConditionVariableCS(&g_pulsar_cond, &g_pulsar_mutex, INFINITE);\n");
        fprintf(f, "    }\n");
        fprintf(f, "    if (g_pulsar_stop && !g_pulsar_queue) { LeaveCriticalSection(&g_pulsar_mutex); break; }\n");
        fprintf(f, "    PulsarWork *work = g_pulsar_queue;\n");
        fprintf(f, "    if (work) g_pulsar_queue = work->next;\n");
        fprintf(f, "    LeaveCriticalSection(&g_pulsar_mutex);\n");
        fprintf(f, "    if (work) { run_function(work->fn_idx); free(work); }\n");
        fprintf(f, "  }\n  return 0;\n}\n\n");
    } else {
        fprintf(f, "static void *pulsar_thread_proc(void *arg) {\n");
        fprintf(f, "  (void)arg;\n");
        fprintf(f, "  for (;;) {\n");
        fprintf(f, "    pthread_mutex_lock(&g_pulsar_mutex);\n");
        fprintf(f, "    while (!g_pulsar_queue && !g_pulsar_stop) {\n");
        fprintf(f, "      pthread_cond_wait(&g_pulsar_cond, &g_pulsar_mutex);\n");
        fprintf(f, "    }\n");
        fprintf(f, "    if (g_pulsar_stop && !g_pulsar_queue) { pthread_mutex_unlock(&g_pulsar_mutex); break; }\n");
        fprintf(f, "    PulsarWork *work = g_pulsar_queue;\n");
        fprintf(f, "    if (work) g_pulsar_queue = work->next;\n");
        fprintf(f, "    pthread_mutex_unlock(&g_pulsar_mutex);\n");
        fprintf(f, "    if (work) { run_function(work->fn_idx); free(work); }\n");
        fprintf(f, "  }\n  return NULL;\n}\n\n");
    }

    fprintf(f, "static void pulsar_spawn(size_t fn_idx) {\n");
    fprintf(f, "  PulsarWork *work = (PulsarWork*)malloc(sizeof(PulsarWork));\n");
    fprintf(f, "  work->fn_idx = fn_idx;\n  work->next = NULL;\n");
    if (target->os == SN_OS_WINDOWS) {
        fprintf(f, "  EnterCriticalSection(&g_pulsar_mutex);\n");
        fprintf(f, "  work->next = g_pulsar_queue;\n  g_pulsar_queue = work;\n");
        fprintf(f, "  WakeConditionVariable(&g_pulsar_cond);\n");
        fprintf(f, "  LeaveCriticalSection(&g_pulsar_mutex);\n");
    } else {
        fprintf(f, "  pthread_mutex_lock(&g_pulsar_mutex);\n");
        fprintf(f, "  work->next = g_pulsar_queue;\n  g_pulsar_queue = work;\n");
        fprintf(f, "  pthread_cond_signal(&g_pulsar_cond);\n");
        fprintf(f, "  pthread_mutex_unlock(&g_pulsar_mutex);\n");
    }
    fprintf(f, "}\n\n");

    /* Emit run_function */
    fprintf(f, "static int run_function(size_t fn_idx) {\n");
    fprintf(f, "  const uint8_t *code = NULL;\n");
    for (size_t i = 0; i < bc->function_count; i++) {
        fprintf(f, "  if (fn_idx == %zu) code = g_fn_code_%zu;\n", i, i);
    }
    fprintf(f, "  if (!code) return 0;\n");
    fprintf(f, "  const uint8_t *ip = code;\n");
    fprintf(f, "  Val locals[256]; memset(locals, 0, sizeof(locals));\n");
    fprintf(f, "  for (;;) {\n");
    fprintf(f, "    uint8_t op = *ip++;\n");
    fprintf(f, "    switch (op) {\n");
    fprintf(f, "    case %d: break;\n", OP_NOP);
    fprintf(f, "    case %d: { Val v; v.tag = VAL_INT; v.as.i = read_i64(&ip); push(v); break; }\n", OP_CONST_INT);
    fprintf(f, "    case %d: { Val v; v.tag = VAL_DOUBLE; v.as.d = read_double(&ip); push(v); break; }\n", OP_CONST_DOUBLE);
    fprintf(f, "    case %d: { Val v; v.tag = VAL_STRING; v.as.str = (char*)g_strings[read_u32(&ip)]; push(v); break; }\n", OP_CONST_STRING);
    fprintf(f, "    case %d: { Val v; v.tag = VAL_BOOL; v.as.b = *ip++ != 0; push(v); break; }\n", OP_CONST_BOOL);
    fprintf(f, "    case %d: { Val v; v.tag = VAL_UNIT; v.as.i = 0; push(v); break; }\n", OP_CONST_UNIT);
    fprintf(f, "    case %d: pop(); break;\n", OP_POP);
    fprintf(f, "    case %d: push(peek(0)); break;\n", OP_DUP);
    fprintf(f, "    case %d: { uint32_t s = read_u32(&ip); push(locals[s]); break; }\n", OP_GET_LOCAL);
    fprintf(f, "    case %d: { uint32_t s = read_u32(&ip); locals[s] = peek(0); break; }\n", OP_SET_LOCAL);
    fprintf(f, "    case %d: { Val b = pop(), a = pop(), r;\n"
               "      if (a.tag == VAL_STRING && b.tag == VAL_STRING) {\n"
               "        size_t la = strlen(a.as.str), lb = strlen(b.as.str);\n"
               "        char *buf = malloc(la + lb + 1); strcpy(buf, a.as.str); strcat(buf, b.as.str);\n"
               "        r.tag = VAL_STRING; r.as.str = buf;\n"
               "      } else if (a.tag == VAL_DOUBLE || b.tag == VAL_DOUBLE) {\n"
               "        r.tag = VAL_DOUBLE; r.as.d = (a.tag == VAL_DOUBLE ? a.as.d : a.as.i) + (b.tag == VAL_DOUBLE ? b.as.d : b.as.i);\n"
               "      } else {\n"
               "        r.tag = VAL_INT; r.as.i = a.as.i + b.as.i;\n"
               "      }\n      push(r); break;\n    }\n", OP_ADD);
    fprintf(f, "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_INT; r.as.i = a.as.i - b.as.i; push(r); break; }\n", OP_SUB);
    fprintf(f, "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_INT; r.as.i = a.as.i * b.as.i; push(r); break; }\n", OP_MUL);
    fprintf(f, "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_INT; r.as.i = b.as.i ? a.as.i / b.as.i : 0; push(r); break; }\n", OP_DIV);
    fprintf(f, "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_INT; r.as.i = b.as.i ? a.as.i %% b.as.i : 0; push(r); break; }\n", OP_MOD);
    fprintf(f, "    case %d: { Val a = pop(), r; r.tag = VAL_INT; r.as.i = -a.as.i; push(r); break; }\n", OP_NEG);
    fprintf(f, "    case %d: { Val a = pop(), r; r.tag = VAL_BOOL; r.as.b = !a.as.b; push(r); break; }\n", OP_NOT);
    fprintf(f, "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_BOOL; r.as.b = (a.as.i == b.as.i); push(r); break; }\n", OP_EQ);
    fprintf(f, "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_BOOL; r.as.b = (a.as.i != b.as.i); push(r); break; }\n", OP_NE);
    fprintf(f, "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_BOOL; r.as.b = (a.as.i < b.as.i); push(r); break; }\n", OP_LT);
    fprintf(f, "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_BOOL; r.as.b = (a.as.i <= b.as.i); push(r); break; }\n", OP_LE);
    fprintf(f, "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_BOOL; r.as.b = (a.as.i > b.as.i); push(r); break; }\n", OP_GT);
    fprintf(f, "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_BOOL; r.as.b = (a.as.i >= b.as.i); push(r); break; }\n", OP_GE);
    fprintf(f, "    case %d: { int32_t off = (int32_t)read_u32(&ip); ip += off; break; }\n", OP_JUMP);
    fprintf(f, "    case %d: { int32_t off = (int32_t)read_u32(&ip); Val c = pop(); if (!c.as.b) ip += off; break; }\n", OP_JUMP_IF_FALSE);
    fprintf(f, "    case %d: { int32_t off = (int32_t)read_u32(&ip); Val c = pop(); if (c.as.b) ip += off; break; }\n", OP_JUMP_IF_TRUE);
    fprintf(f, "    case %d: { uint32_t f = read_u32(&ip); read_u32(&ip); run_function(f); break; }\n", OP_CALL);
    fprintf(f, "    case %d: { Val r = pop(); return (r.tag == VAL_INT ? (int)r.as.i : 0); }\n", OP_RETURN);
    fprintf(f, "    case %d: { uint8_t nl = *ip++; Val v = pop();\n"
               "      if (v.tag == VAL_STRING) printf(\"%%s\", v.as.str);\n"
               "      else if (v.tag == VAL_INT) printf(\"%%ld\", (long)v.as.i);\n"
               "      else if (v.tag == VAL_DOUBLE) printf(\"%%g\", v.as.d);\n"
               "      else if (v.tag == VAL_BOOL) printf(\"%%s\", v.as.b ? \"true\" : \"false\");\n"
               "      if (nl) printf(\"\\n\");\n      break;\n    }\n", OP_PRINT);
    fprintf(f, "    case %d: return 0;\n", OP_HALT);
    fprintf(f, "    default: return 0;\n");
    fprintf(f, "    }\n  }\n}\n\n");

    /* Main entry */
    fprintf(f, "int main(int argc, char **argv) {\n");
    fprintf(f, "  (void)argc; (void)argv;\n");
    if (target->os == SN_OS_WINDOWS) {
        fprintf(f, "  InitializeCriticalSection(&g_pulsar_mutex);\n");
        fprintf(f, "  InitializeConditionVariable(&g_pulsar_cond);\n");
    } else {
        fprintf(f, "  pthread_t pth;\n");
        fprintf(f, "  pthread_create(&pth, NULL, pulsar_thread_proc, NULL);\n");
    }
    fprintf(f, "  int rc = run_function(%u);\n", bc->main_func_idx);
    if (target->os == SN_OS_WINDOWS) {
        fprintf(f, "  EnterCriticalSection(&g_pulsar_mutex);\n");
        fprintf(f, "  g_pulsar_stop = true;\n");
        fprintf(f, "  WakeConditionVariable(&g_pulsar_cond);\n");
        fprintf(f, "  LeaveCriticalSection(&g_pulsar_mutex);\n");
    } else {
        fprintf(f, "  pthread_mutex_lock(&g_pulsar_mutex);\n");
        fprintf(f, "  g_pulsar_stop = true;\n");
        fprintf(f, "  pthread_cond_broadcast(&g_pulsar_cond);\n");
        fprintf(f, "  pthread_mutex_unlock(&g_pulsar_mutex);\n");
        fprintf(f, "  pthread_join(pth, NULL);\n");
    }
    fprintf(f, "  return rc;\n");
    fprintf(f, "}\n");

    fclose(f);

    /* Compile runner C code to final binary using target compiler & flags */
    char cmd[4096];
    snprintf(cmd, sizeof(cmd), "%s %s -o %s %s %s && rm -f %s",
             target->c_compiler, target->cflags, output_path, c_source_path, target->ldflags, c_source_path);

    int status = system(cmd);
    if (status != 0) {
        fprintf(stderr, "error: compilation to native binary failed with exit status %d (command: %s)\n", status, cmd);
        return 0;
    }

#ifndef _WIN32
    chmod(output_path, 0755);
#endif
    return 1;
}
